pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/your-username/cicd-ecommerce-devops.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t ecommerce-app docker/'
      }
    }

    stage('Terraform Apply') {
      steps {
        sh '''
        cd terraform
        terraform init
        terraform apply -auto-approve
        '''
      }
    }

    stage('Deploy with Ansible') {
      steps {
        sh 'ansible-playbook ansible/deploy.yml'
      }
    }
  }
}
